### ISSUE TITLE
Consider using ACF for Commands

### ISSUE THREAD

**Issue by aikar** [GigaGamma/McLink#37]
Hello,

I was searching GitHub for code using TabCompleteEvent to ensure no impact to a change I made in Paper in https://github.com/PaperMC/Paper/commit/54f9e9fb1a8bcef8b97c04bc7e266c58be027c06 and discovered this code.

I just wanted to drop a suggestion to look at my project [ACF](https://acfspigot.emc.gs), as it could save you a ton of time implementing advanced command concepts.

If you decide to use it, see the Spigot thread linked for information on support or to ask questions :)

Good luck!

**Comment by SuperAuguste** [comment]
Hey @aikar, I will consider using ACF as it seems much simpler than our current configuration.
